CREATE TABLE `tblJavelim` (
  `fcName` VARCHAR(18) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL DEFAULT '',
  `fnWins` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `fnGames` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `fnKills` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `fnDeaths` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `fnPredictions` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `fnMVPs` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  `ftLastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE (`fcName`)
) DEFAULT CHARACTER SET ascii COLLATE ascii_general_ci;
